### ISSUE TITLE
When launch qrtun_async_mod.py QRCODE window popups and nothing shows

### ISSUE THREAD

**Issue by GeorgeUgly** [seiferteric/qrtun#2]
Hi,

I'm in a ubuntu 16.04,

Python 2.7.12
pip 19.3.1 from /home/user01/.local/lib/python2.7/site-packages/pip (python 2.7)

There were some errors when I launch like "sudo python python qrtun_async_mod.py 1", 

```
user01@ubuntu:~/qrtun$ sudo python qrtun_async.py 1
Traceback (most recent call last):
  File "qrtun_async.py", line 190, in <module>
    main()
  File "qrtun_async.py", line 170, in main
    tun = QRTun(sys.argv[1])
  File "qrtun_async.py", line 41, in __init__
    self.vc.set(cv2.cv.CV_CAP_PROP_FRAME_HEIGHT, 720)
AttributeError: 'module' object has no attribute 'cv'

```

so I modfied your code to
```
        self.vc.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)
        self.vc.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
```

Then I can launch the py file, but the popups window is empty.
Thus, once the py runs, png files in resource/toscreen2.png is deleted.

Can you help with that?

**Comment by GeorgeUgly** [comment]
In console, "CAM" prints

**Comment by GeorgeUgly** [comment]
I'm running screen 1 first to go through in one box, no 2 screen yet.
